import { Heading, Stack, Text, Button, Link } from '@chakra-ui/react'

const Hero = () => {
  return (
    <Stack
      textAlign={'center'}
      align={'center'}
      spacing={{ base: 8, md: 10 }}
      pt={{ base: 8, md: 10 }}
      pb={{ base: 20, md: 28 }}>
      <Heading
        fontWeight={600}
        fontSize={{ base: '3xl', sm: '4xl', md: '6xl' }}
        lineHeight={'110%'}>
        Weird Punks
      </Heading>
      <Text color={'gray.500'} maxW={'3xl'}>
        Each Weird Punk handcrafted and not generated by AI.
        <br />
        Total supply of only 1000 Weird Punks.
        <br />
        Not affiliated with LarvaLabs
      </Text>
      <Stack spacing={6} direction={'row'}>
        <Button
          as={Link}
          rounded={'full'}
          px={6}
          colorScheme={'orange'}
          bg={'orange.400'}
          _hover={{ bg: 'orange.500' }}
          href='https://opensea.io/collection/weird-punks-collection'>
          View on OpenSea
        </Button>
      </Stack>
    </Stack>
  )
}

export default Hero
