import Events from '@/components/Events'
import Wallet from '@/components/Wallet'
import Bar from '@/components/UI/Bar'
import Footer from '@/components/UI/Footer'
// import AccountModal from '@/components/UI/AccountModal'
import { ReactNode } from 'react'
import { Box, Container } from '@chakra-ui/react'
import Head from 'next/head'

const UI = ({ children }: { children: ReactNode }) => {
  return (
    <Box>
      <Head>
        <title>Weird Punks</title>
        <meta
          name='description'
          content='Each Weird Punk handcrafted and not generated by AI. Total supply of only 1000 Weird Punks. Not affiliated with LarvaLabs'
        />
        <link rel='icon' href='/favicon.gif' type='image/gif' />
      </Head>
      <Events />
      <Wallet />
      <Bar />
      <Container maxW='4xl'>{children}</Container>
      <Footer />
      {/* <AccountModal /> */}
    </Box>
  )
}

export default UI
