import Bar from '@/components/UI/Bar'
import Footer from '@/components/UI/Footer'
import Wallet from '@/components/Wallet'
import { Box, Container } from '@chakra-ui/react'
import Head from 'next/head'
import { ReactNode } from 'react'

const UI = ({ children }: { children: ReactNode }) => {
  return (
    <Box>
      <Head>
        <title>Weird Punks</title>
        <meta
          name='description'
          content='Each Weird Punk is handcrafted, not generated by AI. Total supply is only 1000 Weird Punks.'
        />
        <link rel='icon' href='/favicon.gif' type='image/gif' />
      </Head>
      <Wallet />
      <Bar />
      <Container maxW='4xl' minHeight={'60vh'}>
        {children}
      </Container>
      <Footer />
    </Box>
  )
}

export default UI
